"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import setuptools  

APP = ['dogeThread.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True, 'packages' : ['requests', 'bs4', 'datetime', 'tkinter', 'playsound', 'AppKit']}

setuptools.setup(
    name='doge',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
